// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkDd5TfyXqgppr1dk_jLc-iawEdGC2_Ac',
    appId: '1:1045753947623:web:c96efaa9a8af6d01874942',
    messagingSenderId: '1045753947623',
    projectId: 'proyectowiniot',
    authDomain: 'proyectowiniot.firebaseapp.com',
    databaseURL: 'https://proyectowiniot-default-rtdb.firebaseio.com',
    storageBucket: 'proyectowiniot.firebasestorage.app',
    measurementId: 'G-1P4JEF5R1J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4qGZyxsDSCO4A61f0N5te3SrLvolUk6Y',
    appId: '1:1045753947623:android:a6ddde85e53ead6b874942',
    messagingSenderId: '1045753947623',
    projectId: 'proyectowiniot',
    databaseURL: 'https://proyectowiniot-default-rtdb.firebaseio.com',
    storageBucket: 'proyectowiniot.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVCH_Cjn3uZTZIj80nAhozyM76FbmkbSk',
    appId: '1:1045753947623:ios:aebc73fea25490f6874942',
    messagingSenderId: '1045753947623',
    projectId: 'proyectowiniot',
    databaseURL: 'https://proyectowiniot-default-rtdb.firebaseio.com',
    storageBucket: 'proyectowiniot.firebasestorage.app',
    iosBundleId: 'com.example.flutterVentana',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVCH_Cjn3uZTZIj80nAhozyM76FbmkbSk',
    appId: '1:1045753947623:ios:aebc73fea25490f6874942',
    messagingSenderId: '1045753947623',
    projectId: 'proyectowiniot',
    databaseURL: 'https://proyectowiniot-default-rtdb.firebaseio.com',
    storageBucket: 'proyectowiniot.firebasestorage.app',
    iosBundleId: 'com.example.flutterVentana',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkDd5TfyXqgppr1dk_jLc-iawEdGC2_Ac',
    appId: '1:1045753947623:web:fa81839f229206da874942',
    messagingSenderId: '1045753947623',
    projectId: 'proyectowiniot',
    authDomain: 'proyectowiniot.firebaseapp.com',
    databaseURL: 'https://proyectowiniot-default-rtdb.firebaseio.com',
    storageBucket: 'proyectowiniot.firebasestorage.app',
    measurementId: 'G-LCYV1NQNSQ',
  );
}
